InOut:
  checkpoint_init: null
  experiment_out: /media/hdd/rPSF_result/decode_impl
  data_path: /media/hdd/rPSF_data/crlb_train
Hardware:
  num_worker_train: 2
  device: 'cuda:0'
  unix_niceness: 0
  torch_threads: 2
HyperParameter:
  arch_param:
    activation: ELU
    depth: null
    depth_bg: null
    depth_shared: 2
    depth_union: 2
    init_custom: true
    initial_features: 48
    initial_features_bg: null
    inter_features: 48
    norm: null
    norm_bg: null
    norm_bg_groups: null
    norm_groups: null
    norm_head: null
    norm_head_groups: null
    p_dropout: null
    pool_mode: StrideConv
    recpt_bg: null
    skip_gn_level: null
    up_mode: upsample
    upsample_mode: nearest
    use_last_nl: null
  architecture: SigmaMUNet
  auto_restart_param:
    num_restarts: 5
    restart_treshold: 2000000
  batch_size: 32
  channels_in: 1
  # channels_out: null
  chweight_stat:
  - 1.0
  - 0.0
  disabled_attributes: null
  # ds_lifetime: null
  emitter_label_photon_min: null
  # epoch_0: null
  epochs: 400
  # fgbg_factor: null
  grad_mod: true
  learning_rate_scheduler: ReduceLROnPlateau
  learning_rate_scheduler_param:
    # gamma: 0.9
    # step_size: 8
    factor: 0.1
    patience: 8
  # loss_impl: MixtureModel
  max_number_targets: 100
  moeller_gradient_rescale: false
  opt_param:
    lr: 0.00005 #0.0006
    weight_decay: 0.1
  optimizer: AdamW
  # photon_threshold: null
  # pseudo_ds_size: 10000
Simulation:
  # bg_uniform:
  # - 20.0
  # - 200.0
  # density: null
  # emitter_av: 30
  # emitter_extent:
  # - - -0.5
  #   - 39.5
  # - - -0.5
  #   - 39.5
  # - - -800
  #   - 800
  img_size:
  - 96
  - 96
  # intensity_mu_sig:
  # - 7000.0
  # - 3000.0
  # intensity_th: null
  # lifetime_avg: 1.0
  # mode: acquisition
  # photon_range: null
  psf_extent:
  - - -0.5
    - 95.5
  - - -0.5
    - 95.5
  - null
  # roi_auto_center: false
  # roi_size: null
  # xy_unit: px
Scaling:
  bg_max: 1
  # input_offset: 110.0
  # input_scale: 140.0
  phot_max: 170
  z_max: 20
PostProcessing: SpatialIntegration
PostProcessingParam:
  raw_th: 0.5
TestSet:
  frame_extent:
  - - -0.5
    - 95.5
  - - -0.5
    - 95.5
  - null
  img_size:
  - 96
  - 96
  # mode: simulated
  # test_size: 512
Meta:
  version:
Evaluation:
  dist_ax: 2
  dist_lat: 2
  dist_vol: null
  match_dims: 3