%% Compare 1)ground-truth image 2)image from initial prediction 3)image from prediction after post-pro 
%% D=250 case
nSource = 5;
nt = 1;

%% 1) ground-truth image
mat_path = ['F:\3d_localization\data\test\test_v3\test',num2str(nSource)];
load([mat_path,'\I',num2str(nt),'.mat']);  % mat file for I0
figure; imagesc(I0); title('groundtruth image')

%% pred info
global   Np L Nzones nSource
L = 4; Nzones = 7; Np = 96;
load('data_natural_order_A'); % Single role

pred_path = ['D:\OneDrive - City University of Hong Kong\3dloc\test_result\0910_fft\test',num2str(nSource)];
gt = readtable([pred_path,'\label.txt']);
gt = table2array(gt(:,1:5));
pred = readtable([pred_path,'\loc.csv']);
pred = table2array(pred);
pred_tmp = pred(pred(:,1)==nt,:);

%% 2) image from initial prediction
Vtrue = [pred_tmp(:,3); pred_tmp(:,2); pred_tmp(:,4); pred_tmp(:,5)];
[I01,flux] = PointSources_poisson_v2(length(Vtrue)/4,Vtrue); % flux value in normalized basis case
figure; imagesc(I01); title('image from initial predcition');colorbar

%% 3) image from post-processing prediction
Vpred = [pred_tmp(:,3);pred_tmp(:,2);pred_tmp(:,4);pred_tmp(:,5)];
pred_vol = zeros(size(A));
nPred = length(Vpred)/4;
for i = 1 : nPred
    xlow = min(round(49+Vpred(i)),96); 
    ylow = min(round(49+Vpred(i+ nPred)),96);
    zlow = min(round((Vpred(i+2*nPred)+21)/2.1)+1,20);
    pred_vol(xlow,ylow,zlow)= pred_vol(xlow,ylow,zlow)+Vpred(i+3*nPred);
end

[xIt, elx, ely, elz] = local_3Dmax_large(pred_vol);

% Iterative Scheme on refinment on estimation of flux & Evaluation
idx_est = find(xIt>0); 
% load([mat_path,'\im',num2str(nt),'.mat']);  % mat file for g
% flux_est_var = Iter_flux(A, idx_est, g, b);
flux_est_dnn = xIt(idx_est);
[loc_x,loc_y,loc_z] = ind2sub(size(A),find(xIt>0)); 
Vtrue = [loc_x-49;loc_y-49;(loc_z-1)*2.1-21;flux_est_dnn];
[I02,flux] = PointSources_poisson_v2(length(Vtrue)/4,Vtrue); % flux value in normalized basis case
figure; imagesc(I02); title('image from post-processing predcition');colorbar


% %% D=21 case
% nSource = 5;
% pred_path = ['D:\OneDrive - City University of Hong Kong\3dloc\test_result\0819_fft_conv\test',num2str(nSource)];
% % pred_path = ['D:\OneDrive - City University of Hong Kong\3dloc\test_result\0000_unifluxtrain\test_v3\test',num2str(nSource)];
% gt = readtable([pred_path,'\label.txt']);
% gt = table2array(gt(:,1:5));
% % pred = readtable([pred_path,'\loc.csv']);
% pred = readtable([pred_path,'\loc_bool.csv']);
% pred = table2array(pred);
% 
% id = 2;
% pred_tmp = pred(pred(:,1)==id,:);
% 
% max_pred = max(pred_tmp(:,5));
% pred_tmp = pred_tmp(pred_tmp(:,5)>max_pred*0.002,:);
% 
% Vtrue = [pred_tmp(:,2)-49; pred_tmp(:,3)-49; pred_tmp(:,4); pred_tmp(:,5)];
% 
% [I01,flux] = PointSources_poisson_v2(length(Vtrue)/4,Vtrue); % flux value in normalized basis case
% figure; imagesc(I01)

% %% compare img generated by gt and load I0
% id = 16;
% 
% mat_path = 'F:\3d_localization\data\test\test_v3_1st\test5\';
% load([mat_path,'\I',num2str(id),'.mat']);  % mat file for I0
% figure; imagesc(I0.'); title('load I0')
% 
% gt = readtable([mat_path,'\label.txt']);
% gt = table2array(gt(:,1:5));
% gt_tmp = gt(gt(:,1)==id,:);
% Vtrue = [gt_tmp(:,3); gt_tmp(:,2); gt_tmp(:,4); gt_tmp(:,5)];
% [I01,flux] = PointSources_poisson_v2(length(Vtrue)/4,Vtrue); % flux value in normalized basis case
% figure; imagesc(I01.')







