Camera:
  baseline: 398.6
  convert2photons: true
  e_per_adu: 5.0
  em_gain: 100.0
  px_size:
  - 127.0
  - 117.0
  qe: 1.0
  read_sigma: 58.8
  spur_noise: 0.0015
Hardware:
  device: cpu
  device_simulation: cpu
HyperParameter:
  batch_size: 64
  channels_in: 1
  opt_param:
    lr: 0.0006
  optimizer: AdamW
InOut:
  calibration_file: /home/lingjia/Documents/rPSF/NN/spline_calibration_3dcal.mat
  experiment_out: /media/hdd/rPSF_results/decode_impl
Simulation:
  bg_uniform:
  - 20.0
  - 200.0
  density:
  emitter_av: 25
  emitter_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  - - -800
    - 800
  img_size:
  - 40
  - 40
  intensity_mu_sig:
  - 7000.0
  - 3000.0
  lifetime_avg: 1.0
  photon_range:
  psf_extent:
  - - -0.5
    - 39.5
  - - -0.5
    - 39.5
  -
